### ISSUE TITLE
Different viewers for different image types; is it possible?

### ISSUE THREAD

**Issue by fmeyenhofer** [ome/omero-gallery#17]
In OMERO we use different viewers depending on the image file type. Is there a way to configure this yet?

**Comment by will-moore** [comment]
Are you using your own custom viewers, or one's you've installed from OME, e.g. iviewer?
For your own viewer, you can customise when it's used in your views.py code: See https://docs.openmicroscopy.org/omero/5.3.5/developers/Web/LinkingFromWebclient.html#custom-image-viewer
