### ISSUE TITLE
Add "clear/reset filter" button or link

### ISSUE THREAD

**Issue by abhamacher** [ome/omero-gallery#76]
Hi Will,

once a user performs a specific search in the 'categories' UI, the user is somewhat stuck in the filtered search view. As user you can still change the filter to modify your search result but you can't reset it to get back to the original entry page (e.g. for browsing the listed predefined studies). Of course a user can click on the banner image on the top left to get back to the main page, but this is not very intuitive. So my suggestion would be to add a "clear filter" or "reset filter" button or link on the search results page close to the search filter menu to improve the usability.

Happy new Year :-)
Anna

**Comment by will-moore** [comment]
Thanks for the feedback. It shouldn't be too much work to add that.
